
#ifndef _GL_CONFIG_H_
#define _GL_CONFIG_H_


#define CONFIG_RSA_PUBKEY_START 		(0x9f05ffff - 0x1000)
#define CONFIG_RSA_PUBKEY_MAX_SIZE 		0x800 // 2k
#define CONFIG_AES_KEY_START 			(CONFIG_RSA_PUBKEY_START + CONFIG_RSA_PUBKEY_MAX_SIZE)
#define CONFIG_AES_KEY_MAX_SIZE 		0X400

#define CONFIG_FW_SIG_START 			0x9FFF0000
#define CONFIG_SIGN_PADDING_LEN 		0x10000

#define CONFIG_SIGN_LEN 				2
#define CONFIG_SIGN_FLAG_LEN 			4
#define CONFIG_DEADCODE_LEN 			4



#define CONFIG_STATUS_DOWNLOAD_FW 		1
#define CONFIG_STATUS_UPDATE_SIGN 		2



#define CHECK_ART_REGION
//#undef CHECK_ART_REGION

#ifndef DEBUG_UIP
#define DEBUG_UIP
#endif

#define CONFIG_UBOOT_START 			0xf0000
#define CONFIG_UBOOT_SIZE 			0x80000 // 0x100000// 
#define CONFIG_ART_START 			(CONFIG_UBOOT_START + CONFIG_UBOOT_SIZE)
#define CONFIG_ART_SIZE 			0x10000
#define CONFIG_FIRMWARE_START		(CONFIG_ART_START + CONFIG_ART_SIZE)
#define CONFIG_FIRMWARE_SIZE		0x1E80000 //0x1a00000
//#define CONFIG_RSA_PUBKEY_START 	(CONFIG_FIRMWARE_START - 0x1000) //0x17F000
//#define CONFIG_RSA_PUBKEY_MAX_SIZE 	0x800 // 2k
//#define CONFIG_AES_KEY_START    	(CONFIG_RSA_PUBKEY_START + CONFIG_RSA_PUBKEY_MAX_SIZE)
//#define CONFIG_AES_KEY_MAX_SIZE 	0x80 // 128b

#define GL_OK 0
#define GL_FAILED -1

#define GL_IPQ40XX_CMD_RUN
//#undef GL_IPQ40XX_CMD_RUN

#define WEBFAILSAFE_UPLOAD_RAM_ADDRESS			0x84000000
#define WEBFAILSAFE_UPLOAD_UBOOT_SIZE_IN_BYTES		( 512 * 1024 )
#define WEBFAILSAFE_UPLOAD_ART_SIZE_IN_BYTES		( 64 * 1024 )


#define CONFIG_UBOOT_NAME 	"uboot-gl-b1300.bin"
#define CONFIG_LEDE_FW_NAME "lede-gl-b1300.bin"
#define CONFIG_QSDK_FW_NAME "qsdk-gl-b1300.bin"
#define CONFIG_CFG_NAME 	"config-gl-b1300.bin"


/*GPIO*/
//#define GPIO_2GWiFi_LED   3
//#define GPIO_5GWiFi_LED   2
#define GPIO_SW_RESET_BTN 63
#define GPIO_VAL_BTN_PRESSED	0
#define LED_ON	1
#define LED_OFF 0

#define GPIO_POWER_LED 0
#define GPIO_MESH_LED 1
#define GPIO_WIFI_LED 2

#define GPIO_RESET_BTN 10

// U-Boot partition size and offset
#define WEBFAILSAFE_UPLOAD_UBOOT_ADDRESS		0x84000000
#define UPDATE_SCRIPT_UBOOT_SIZE_IN_BYTES		"0x80000"

// Firmware partition offset
#define WEBFAILSAFE_UPLOAD_KERNEL_ADDRESS		CFG_KERN_ADDR

// ART partition size and offset
#define WEBFAILSAFE_UPLOAD_ART_ADDRESS			CFG_FACTORY_ADDR


// max. firmware size <= (FLASH_SIZE -  WEBFAILSAFE_UPLOAD_LIMITED_AREA_IN_BYTES)
#define WEBFAILSAFE_UPLOAD_LIMITED_AREA_IN_BYTES	( 320 * 1024 )

// progress state info
#define WEBFAILSAFE_PROGRESS_START			0
#define WEBFAILSAFE_PROGRESS_TIMEOUT			1
#define WEBFAILSAFE_PROGRESS_UPLOAD_READY		2
#define WEBFAILSAFE_PROGRESS_UPGRADE_READY		3
#define WEBFAILSAFE_PROGRESS_UPGRADE_FAILED		4

// update type
#define WEBFAILSAFE_UPGRADE_TYPE_FIRMWARE		0
#define WEBFAILSAFE_UPGRADE_TYPE_UBOOT			1
#define WEBFAILSAFE_UPGRADE_TYPE_ART			2
#define WEBFAILSAFE_UPGRADE_TYPE_QSDK_FIRMWARE	3

#define CONFIG_NET_MULTI

#define CONFIG_MAX_UBOOT_SIZE ( 512 * 1024 )

int rsa_verify(ulong filesize);

#endif