
#ifndef _GL_CONFIG_H_
#define _GL_CONFIG_H_

#define CONFIG_RSA
#undef CONFIG_RSA

#define CONFIG_RSA_PUBKEY_START 	(0x180000 - 0x1000)
#define CONFIG_RSA_PUBKEY_MAX_SIZE 	0x800 // 2k
#define CONFIG_AES_KEY_START (CONFIG_RSA_PUBKEY_START + CONFIG_RSA_PUBKEY_MAX_SIZE)
#define CONFIG_AES_KEY_MAX_SIZE 0X400
#define CONFIG_FW_SIG_START (CONFIG_AES_KEY_START + CONFIG_AES_KEY_MAX_SIZE)
#define CONFIG_FW_SIG_MAX_SIZE 0X400

#define CONFIG_SIGN_LEN 2
#define CONFIG_SIGN_FLAG_LEN 4
#define CONFIG_DEADCODE_LEN 4
#define CONFIG_SIGN_PADDING_LEN 0x10000


#define CONFIG_STATUS_DOWNLOAD_FW 	1
#define CONFIG_STATUS_UPDATE_SIGN 	2

#endif